spring.application.name=notification-api

# Server
server.port=8080

# Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/notifications
spring.datasource.username=notif_user
spring.datasource.password=notif_pass

# Hibernate / JPA settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Redis
spring.redis.host=localhost
spring.redis.port=6379

#This is to override the time-zone with default "Asia/Calcutta" because postgres understood "Asia/Kolkata"
spring.jackson.time-zone=Asia/Kolkata

